# Site settings
title: Preston's Website
email: Pcoppage@albany.edu
description: Preston is awesome.
url: https://pcoppage.github.io
github_username: pcoppage

# Build settings
markdown: kramdown
permalink: pretty
